source 'https://rubygems.org'

gem 'rails',                                  '~> 4.0.1'
gem 'sqlite3',                                '~> 1.3.8'
gem 'sass-rails',                             '~> 4.0.0'
gem 'uglifier',                               '~> 2.3.2'
gem 'coffee-rails',                           '~> 4.0.0'
gem 'turbolinks',                             '~> 1.3.1'
gem 'jbuilder',                               '~> 1.5.2'

group :test do
  gem 'rspec-rails',                          '~> 2.14.0'
  gem 'shoulda-matchers',                     '~> 2.4.0'
  gem 'factory_girl_rails',                   '~> 4.3.0'
end

group :development do
  gem 'pry-rails',                            '~> 0.3.2'
  gem 'thin',                                 '~> 1.6.1'
end
