source 'https://rubygems.org'

gem 'rails',                                  '~> 4.0.1'
gem 'sqlite3',                                '~> 1.3.8'
gem 'sass-rails',                             '~> 4.0.0'
gem 'uglifier',                               '~> 2.3.2'
gem 'coffee-rails',                           '~> 4.0.0'
gem 'jquery-rails',                           '~> 3.0.4'
gem 'turbolinks',                             '~> 1.3.1'
gem 'jbuilder',                               '~> 1.5.2'

group :test, :development do
  gem 'rspec-rails',                          '~> 2.14.0'
end
