
#development:
#  adapter: postgresql
#  host: localhost
#  database: projects-dev
#  pool: 5
#  timeout: 5000
#  encoding: unicode
#  user: postgres
#  password: postgres
#

#test:
#  adapter: postgresql
#  host: localhost
#  database: projects-test
#  pool: 5
#  timeout: 5000
#  encoding: unicode
#  user: postgres
#  password: postgres

#development:
#  adapter: postgresql
#  host: localhost
#  database: pm-dev
#  pool: 5
#  timeout: 5000
#  encoding: unicode
#  user: postgres
#  password: postgres
#
#
#test:
#  adapter: postgresql
#  host: localhost
#  database: pm-test
#  pool: 5
#  timeout: 5000
#  encoding: unicode
#  user: postgres
#  password: postgres


production:
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode